src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 * @Vich\Uploadable
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Producteur", inversedBy="unite")
     */
    private $producteur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $unite;

    /**
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="filename")
     * @var File|null
     */
    private $imageFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filename;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getProducteur(): ?Producteur
    {
        return $this->producteur;
    }

    public function setProducteur(?Producteur $producteur): self
    {
        $this->producteur = $producteur;

        return $this;
    }

    public function getUnite(): ?string
    {
        return $this->unite;
    }

    public function setUnite(string $unite): self
    {
        $this->unite = $unite;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Produit
     */
    public function setFilename(?string $filename): Produit
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Produit
     */
    public function setImageFile(?File $imageFile): Produit
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Producteur;
use App\Entity\Produit;
use App\Form\ProduitType1;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/user")
 * @IsGranted("ROLE_USER")
 */
class UserController extends AbstractController
{

    private $produitRepository;



    public function __construct(ProduitRepository $produitRepository)
    {
        $this->produitRepository=$produitRepository;
    }

    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(): Response
    {
        $user= $this->getUser();
        $produits = $this->produitRepository->findByProducteur($user->getId());
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
            'produits'=> $produits
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType1::class, $produit);
        $form->handleRequest($request);
        $user= $this->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
            $producteur=new Producteur();
            $producteur=$user;
            $produit->setProducteur($producteur);
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(Produit $produit): Response
    {
        return $this->render('user/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Produit $produit): Response
    {
        $form = $this->createForm(ProduitType1::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Produit $produit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': produit.id}) }}" onsubmit="return confirm('Es tu sure de vouloir supprimer le produit ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron">
            <h1>Edit Produit</h1>

            {{ include('user/_form.html.twig', {'button_label': 'Modifier'}) }}

            <a href="{{ path('user_index') }}" class="btn btn-primary m-2">Retour</a>

            {{ include('user/_delete_form.html.twig') }}
        </div>
    </div>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    <div class="container">
<div class="jumbotron mt-5">
    <h1>Liste de mes produits</h1>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Unite</th>
                <th>Image</th>
                <th>Description</th>
                <th>Prix</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.nom }}</td>
                <td>{{ produit.unite }}</td>
                <td> {% if produit.filename %}
                        <img src="/images/products/{{ produit.filename }}" alt="image de {{ produit.nom }}" style="width: 286px;height: 218px " >
                    {% endif %}</td>
                <td>{{ produit.description }}</td>
                <td>{{ produit.prix }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': produit.id}) }}" class="btn btn-secondary">Voir détails</a>
                    <a href="{{ path('user_edit', {'id': produit.id}) }}" class="btn btn-danger mt-2">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}" class="btn btn-success">Nouveau produit</a>
</div>
    </div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau produit{% endblock %}

{% block body %}
    <div class="container">
    <div class="jumbotron mt-5">
    <h1>Créer un nouveau produit</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}" class="btn btn-secondary">retour</a>
    </div></div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron">
            <h1>Produit</h1>

            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ produit.id }}</td>
                </tr>
                <tr>
                    <th>Nom</th>
                    <td>{{ produit.nom }}</td>
                </tr>
                <tr>
                    <th>Unite</th>
                    <td>{{ produit.unite }}</td>
                </tr>
                <tr>
                    <th>Filename</th>
                    <td>{{ produit.filename }}</td>
                </tr>
                <tr>
                    <th>date de Modification</th>
                    <td>{{ produit.updatedAt ? produit.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Prix</th>
                    <td>{{ produit.prix }}</td>
                </tr>
                </tbody>
            </table>

            <a href="{{ path('user_index') }}" class="btn btn-secondary">retour</a>

            <a href="{{ path('user_edit', {'id': produit.id}) }}" class="btn btn-primary mt-2">editer</a>

            {{ include('user/_delete_form.html.twig') }}
        </div>
    </div>

{% endblock %}